In [49]:
import pandas as pd
from datasets import Dataset
import torch
from transformers import BartTokenizer, AutoModelForSeq2SeqLM
from transformers import DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer

## Collecting Data

### Scrapping data

In [ ]:
# import requests
# from bs4 import BeautifulSoup
# from newspaper import Article
# import pandas as pd
# import time

# headers = {
#     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'
# }

# keyword = "kebakaran"
# daftar_berita = []

# target_halaman = 1000

# print(f"Target: {target_halaman} Halaman dari Detik.com...\n")

# for page in range(1, target_halaman + 1):
#     url_pencarian = f"https://www.detik.com/search/searchall?query={keyword}&page={page}"

#     print(f"==========================================")
#     print(f"Membuka Halaman {page}...")

#     try:
#         response = requests.get(url_pencarian, headers=headers)
#         soup = BeautifulSoup(response.text, 'html.parser')

#         artikel_elements = soup.find_all('article')

#         if not artikel_elements:
#             print(f"Halaman {page} kosong. Pencarian selesai!")
#             break

#         for item in artikel_elements:
#             link_tag = item.find('a')

#             if link_tag and 'href' in link_tag.attrs:
#                 url_berita = link_tag['href']

#                 # --- FITUR EXCLUDE ---
#                 if '20.detik.com' in url_berita or 'foto.detik.com' in url_berita:
#                     continue

#                 try:
#                     artikel = Article(url_berita, language='id')
#                     artikel.download()
#                     artikel.parse()

#                     judul = artikel.title
#                     teks_full = artikel.text

#                     if judul.startswith('Video:') or judul.startswith('Foto:'):
#                         continue

#                     # --- FITUR CLEANING ---
#                     teks_full = teks_full.replace('SCROLL TO CONTINUE WITH CONTENT', '')
#                     teks_full = teks_full.replace('Saksikan Live DetikSore:', '')
#                     teks_full = teks_full.replace('ADVERTISEMENT', '') # Tambahan dari evaluasi sebelumnya
#                     teks_full = " ".join(teks_full.split())

#                     if len(teks_full) > 500:
#                         daftar_berita.append({
#                             "judul": judul,
#                             "url": url_berita,
#                             "teks_berita": teks_full
#                         })
#                         print(f"=> [DAPAT!] {url_berita}")

#                 except Exception as e:
#                     pass
#                 time.sleep(1)

#     except Exception as e:
#         print(f"Gagal memuat Halaman {page}")

#     time.sleep(3)

# # Simpan CSV
# df = pd.DataFrame(daftar_berita)
# print("\n==========================================")
# if len(df) > 0:
#     #df.to_csv("dataset_detik_kebakaran.csv", index=False)
#     print(f"SUPER SEKALI! Berhasil menyimpan {len(df)} berita ke CSV.")
# else:
#     print("Gagal mengumpulkan data.")

In [ ]:
# import pandas as pd

# file_name = "dataset_detik_kebakaran.csv"
# df = pd.read_csv(file_name)

# print(f"Total data awal: {len(df)} baris.\n")
# keyword_sampah = ""
# mask_sampah = df['teks_berita'].str.contains(keyword_sampah, case=False, na=False)

# # Hitung jumlahnya
# df_sampah = df[mask_sampah]
# print(f"Ditemukan {len(df_sampah)} baris yang mengandung kata '{keyword_sampah}'.")

# if len(df_sampah) > 0:
#     print("\n--- Preview Berita yang Akan Dihapus ---")
#     display(df_sampah[['judul', 'teks_berita']].head(10))

In [ ]:
## Filterring Data

# df_bersih = df[~mask_sampah].copy()

# print(f"\n Proses pembersihan selesai!")
# print(f"Total data setelah dibersihkan: {len(df_bersih)} baris.")

# nama_file_baru = "dataset_detik_kebakaran.csv"
# df_bersih.to_csv(nama_file_baru, index=False)
# print(f"Dataset super bersih berhasil disimpan sebagai '{nama_file_baru}'")

### Labelling

In [ ]:
# import google.generativeai as genai
# import pandas as pd
# import time
# import asyncio
# # 1. Konfigurasi API
# genai.configure(api_key="AIzaSyA2A70w2UyO7iZDq7OA2AQnJMBZAUqGXhY")
# model = genai.GenerativeModel('gemma-4-31b-it')

# # 2. Load Dataset Hasil Scrapping Kemarin
# df = pd.read_csv("dataset_detik_kebakaran.csv")
# # Ingat limit harian 1.500 RPD! Kita ambil 1.500 data pertama untuk "Cicilan Hari 1"
# df_hari_ini = df.head(1000).copy()

# # 3. Fungsi Asynchronous untuk nembak API
# async def fetch_summary(text, index):
#     prompt = f"""
#     Anda adalah sistem ekstraksi berita. Buat ringkasan abstrak maksimal 3 kalimat padat yang mengandung unsur 5W1H dari berita yang diberikan. Gunakan bahasa Indonesia baku dan lugas.

#     --- CONTOH ---
#     Berita: Sebuah gudang penyimpanan ban bekas di wilayah Tajurhalang, Kabupaten Bogor, mengalami kebakaran dahsyat pada Selasa sore. Asap hitam pekat membumbung tinggi dan sempat mengganggu pandangan pengendara yang melintas di jalan raya terdekat. Kepala Dinas Pemadam Kebakaran setempat menyatakan bahwa proses pemadaman memakan waktu lebih dari tiga jam karena material karet yang terbakar sangat sulit dipadamkan. Beruntung tidak ada pekerja di lokasi saat kejadian.
#     Ringkasan: Gudang ban bekas di Tajurhalang, Bogor ludes terbakar pada Selasa sore. Proses pemadaman berlangsung selama tiga jam karena material karet yang sulit dipadamkan. Tidak ada korban jiwa dalam peristiwa tersebut.

#     --- TUGAS UTAMA ---
#     Berita: {text}
#     Ringkasan:
#     """
#     try:
#         response = await model.generate_content_async(prompt)
#         return index, response.text
#     except Exception as e:
#         print(f"Error di index {index}: {e}")
#         return index, "ERROR"

# # 4. Fungsi Utama pengatur Gelombang (Batching)
# async def main():
#     hasil_ringkasan = [""] * len(df_hari_ini)
#     ukuran_batch = 12 # Eksekusi 12 data sekaligus (Aman di bawah limit 15 RPM)

#     print(f"Memulai proses Asynchronous untuk {len(df_hari_ini)} data...")
#     print(f"Strategi: {ukuran_batch} request berbarengan per menit.\n")

#     # Memotong data menjadi gelombang-gelombang kecil (batches)
#     for i in range(0, len(df_hari_ini), ukuran_batch):
#         batch_df = df_hari_ini.iloc[i:i+ukuran_batch]

#         print(f"Hit api {i//ukuran_batch + 1} (Data {i} sampai {i+len(batch_df)-1})...")

#         tasks = []
#         for index, row in batch_df.iterrows():
#             # Kita simpan posisinya agar hasil kembaliannya nggak tertukar
#             posisi_asli = i + (index - batch_df.index[0])
#             tasks.append(fetch_summary(row['teks_berita'], posisi_asli))

#         # Eksekusi semua tugas di gelombang ini secara BERBARENGAN!
#         hasil_batch = await asyncio.gather(*tasks)
#         # Simpan hasilnya ke list utama sesuai posisinya
#         for posisi, teks_hasil in hasil_batch:
#             hasil_ringkasan[posisi] = teks_hasil

#         print("Gelombang selesai! Pendinginan mesin 60 detik untuk reset RPM Google...\n")
#         time.sleep(60) # Tidur 1 menit untuk menghindari Error 429

#     return hasil_ringkasan:

# hasil_akhir = await main()

# df_hari_ini['ringkasan_gemini'] = hasil_akhir
# df_hari_ini.to_csv("dataset_summary.csv", index=False)

## DATA PREPROCESSING

In [54]:
# dfSummary = pd.read_csv("dataset_summary.csv")
# dfSummary['ringkasan_gemini'].head(10)

In [ ]:
# df = pd.read_csv("/content/dataset_summary_clean.csv")

# def ekstrak_ringkasan_asli(text):
#     if pd.isna(text):
#         return text

#     # Pecah teks berdasarkan garis baru (Enter)
#     baris_teks = str(text).strip().split('\n')

#     # Ambil baris teks terakhir yang tidak kosong
#     for baris in reversed(baris_teks):
#         if baris.strip():
#             return baris.strip()

#     return text

# print("membersihkan 'Chain of Thought' dari Gemma...")
# df['ringkasan_bersih'] = df['ringkasan_gemini'].apply(ekstrak_ringkasan_asli)

# df_final = df[['judul', 'url', 'teks_berita', 'ringkasan_bersih']]

# print("\n=== PREVIEW HASIL BERSIH ===")
# display(df_final[['teks_berita', 'ringkasan_bersih']].head(3))

# nama_file = "dataset_summary_clean.csv"
# df_final.to_csv(nama_file, index=False)

In [57]:
df = df_final.copy()
df.head()

,judul,url,teks_berita,ringkasan_bersih
0,Pabrik Penggilingan Padi di Ciamis Terbakar!,https://www.detik.com/jabar/berita/d-8449753/p...,"Malam yang tenang di Dusun Cijulang, Desa Ciju...",Bangunan penggilingan padi milik Cucu Hidayat ...
1,Lara 5 Orang Sekeluarga di Jakbar Tewas saat R...,https://news.detik.com/berita/d-8449738/lara-5...,Lima orang tewas dalam insiden kebakaran rumah...,"Kebakaran rumah di Grogol Petamburan, Jakarta ..."
2,Petugas Damkar Terluka Saat Padamkan Kebakaran...,https://news.detik.com/berita/d-8449210/petuga...,Kebakaran di asrama polisi yang berlokasi di K...,"Kebakaran melanda asrama polisi di Kalideres, ..."
3,Pikap Tahu Bulat Hangus Terbakar di Umbulharjo...,https://www.detik.com/jogja/berita/d-8449198/p...,Satu unit mobil bak terbuka atau pikap pedagan...,Satu unit mobil pikap pedagang tahu bulat terb...
4,Investigasi Awal Penyebab Markas BYD Kebakaran...,https://oto.detik.com/mobil-listrik/d-8449133/...,Baru-baru ini terjadi kebakaran di kantor pusa...,Kebakaran melanda garasi parkir kendaraan uji ...

In [ ]:
from datasets import Dataset

# 1. Konversi Pandas DataFrame ke Hugging Face Dataset
hf_dataset = Dataset.from_pandas(df_final)

# 2. Split dataset menjadi Train (90%) dan Test/Eval (10%)
hf_dataset_split = hf_dataset.train_test_split(test_size=0.1, seed=42)

print("\nBentuk Dataset setelah di-split:")
print(hf_dataset_split)

# 3. Aplikasikan preprocess_function untuk memetakan fitur (teks_berita) dan label (ringkasan_bersih)
print("\nSedang melakukan tokenisasi data...")
tokenized_datasets = hf_dataset_split.map(preprocess_function, batched=True)

print("\nSelesai! Data siap di-training.")

Bentuk Dataset setelah di-split:
DatasetDict({
    train: Dataset({
        features: ['judul', 'url', 'teks_berita', 'ringkasan_bersih'],
        num_rows: 717
    })
    test: Dataset({
        features: ['judul', 'url', 'teks_berita', 'ringkasan_bersih'],
        num_rows: 80
    })
})

Sedang melakukan tokenisasi data...

Map:   0%|          | 0/717 [00:00<?, ? examples/s]

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

Selesai! Data siap di-training.

## Training

In [ ]:
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 1. Load model dan tokenizer menggunakan Auto
model_checkpoint = "google/mt5-small"

# AutoTokenizer dan AutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq

model_checkpoint = "google/mt5-small"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

prefix = "summarize: "
max_input_length = 512
max_target_length = 128

def preprocess_function(examples):
    inputs = [prefix + doc for doc in examples["teks_berita"]]

    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

    # Gunakan kolom 'ringkasan_bersih' sebagai label
    labels = tokenizer(text_target=examples["ringkasan_bersih"], max_length=max_target_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint, tie_word_embeddings=False)
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir="./mt5-summarization-indonesia-v2", 
    eval_strategy="epoch",
    learning_rate=1e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    weight_decay=0.01,
    num_train_epochs=5,
    predict_with_generate=True,
    optim="adamw_torch",
    fp16=False,         
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
)

# training
trainer.train()

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=900, training_loss=4.1490229627821185, metrics={'train_runtime': 740.9157, 'train_samples_per_second': 4.839, 'train_steps_per_second': 1.215, 'total_flos': 1888797167247360.0, 'train_loss': 4.1490229627821185, 'epoch': 5.0})

In [ ]:
trainer.save_model("./model-summary-finalv3")
print("Model dan tokenizer berhasil disimpan!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model dan tokenizer berhasil disimpan!

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 1. Load model dan tokenizer 
path_model = "./model-summary-finalv3"
tokenizer = AutoTokenizer.from_pretrained(path_model)
model = AutoModelForSeq2SeqLM.from_pretrained(path_model)

teks_berita_baru = """
Dukung Kesiapsiagaan Karhutla, Dewan Minta Pengawasan Diperkuat
PALANGKA RAYA, PROKALTENG.CO– Upaya Pemerintah Kota Palangka Raya melalui BPBD dalam mematangkan kesiapsiagaan menghadapi potensi kebakaran hutan dan lahan (karhutla) mendapat dukungan dari DPRD Kota Palangka Raya.

Wakil Ketua I Komisi II DPRD Kota Palangka Raya, Hap Baperdu menilai langkah antisipatif melalui rapat koordinasi lintas instansi serta patroli terpadu merupakan langkah yang tepat, mengingat prediksi musim kemarau tahun ini datang lebih awal.

“Kami mendukung penuh kesiapsiagaan pemerintah kota. Apalagi berdasarkan prakiraan, musim kemarau akan lebih kering sehingga potensi karhutla meningkat,” ujarnya saat dimintai tanggapan, Rabu (22/4/2026).

Ia menekankan, selain kesiapan personel dan sarana prasarana, pengawasan di lapangan harus diperkuat. Terutama di wilayah rawan seperti Kecamatan Jekan Raya, Pahandut, dan Sebangau yang kerap terjadi kebakaran lahan.

Menurutnya, peran masyarakat juga menjadi kunci dalam pencegahan karhutla, sehingga sosialisasi harus terus digencarkan hingga tingkat kelurahan.

“Pembentukan Kelurahan Tangguh Bencana ini bagus, tinggal bagaimana implementasinya benar-benar berjalan. Masyarakat harus dilibatkan aktif, karena sebagian besar kasus karhutla dipicu oleh aktivitas manusia,” jelasnya.

Lebih lanjut, ia meminta pemerintah kota memastikan ketersediaan peralatan pemadaman serta dukungan anggaran yang memadai, agar penanganan dapat dilakukan secara cepat dan efektif saat terjadi kebakaran.

“Jangan sampai saat kejadian, kita terkendala alat atau sumber daya. Antisipasi harus lebih diutamakan daripada penanganan,” tegasnya.

Ia juga mengimbau masyarakat untuk tidak membuka lahan dengan cara membakar, karena selain melanggar hukum, juga berpotensi menimbulkan dampak luas bagi lingkungan dan kesehatan.(jef)

PALANGKA RAYA, PROKALTENG.CO– Upaya Pemerintah Kota Palangka Raya melalui BPBD dalam mematangkan kesiapsiagaan menghadapi potensi kebakaran hutan dan lahan (karhutla) mendapat dukungan dari DPRD Kota Palangka Raya.

Wakil Ketua I Komisi II DPRD Kota Palangka Raya, Hap Baperdu menilai langkah antisipatif melalui rapat koordinasi lintas instansi serta patroli terpadu merupakan langkah yang tepat, mengingat prediksi musim kemarau tahun ini datang lebih awal.

“Kami mendukung penuh kesiapsiagaan pemerintah kota. Apalagi berdasarkan prakiraan, musim kemarau akan lebih kering sehingga potensi karhutla meningkat,” ujarnya saat dimintai tanggapan, Rabu (22/4/2026).

Ia menekankan, selain kesiapan personel dan sarana prasarana, pengawasan di lapangan harus diperkuat. Terutama di wilayah rawan seperti Kecamatan Jekan Raya, Pahandut, dan Sebangau yang kerap terjadi kebakaran lahan.

Menurutnya, peran masyarakat juga menjadi kunci dalam pencegahan karhutla, sehingga sosialisasi harus terus digencarkan hingga tingkat kelurahan.

“Pembentukan Kelurahan Tangguh Bencana ini bagus, tinggal bagaimana implementasinya benar-benar berjalan. Masyarakat harus dilibatkan aktif, karena sebagian besar kasus karhutla dipicu oleh aktivitas manusia,” jelasnya.

Lebih lanjut, ia meminta pemerintah kota memastikan ketersediaan peralatan pemadaman serta dukungan anggaran yang memadai, agar penanganan dapat dilakukan secara cepat dan efektif saat terjadi kebakaran.

“Jangan sampai saat kejadian, kita terkendala alat atau sumber daya. Antisipasi harus lebih diutamakan daripada penanganan,” tegasnya.

Ia juga mengimbau masyarakat untuk tidak membuka lahan dengan cara membakar, karena selain melanggar hukum, juga berpotensi menimbulkan dampak luas bagi lingkungan dan kesehatan.(jef)

"""

teks_input = "summarize: " + teks_berita_baru

# 4. Ubah teks jadi token
inputs = tokenizer(teks_input, return_tensors="pt", max_length=512, truncation=True)

# 5. Minta model membuat ringkasan
summary_ids = model.generate(
    inputs["input_ids"],
    max_length=100,      # Panjang maksimal ringkasan
    min_length=10,      # Panjang minimal ringkasan
    num_beams=4,        # Teknik pencarian kata terbaik
    early_stopping=True
)

# 6. Ubah token hasil kembali jadi teks
hasil_ringkasan = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Teks Asli:", teks_berita_baru)
print("----------------------------")
print("Hasil Ringkasan Modelmu:", hasil_ringkasan)

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Teks Asli:
Dukung Kesiapsiagaan Karhutla, Dewan Minta Pengawasan Diperkuat
PALANGKA RAYA, PROKALTENG.CO– Upaya Pemerintah Kota Palangka Raya melalui BPBD dalam mematangkan kesiapsiagaan menghadapi potensi kebakaran hutan dan lahan (karhutla) mendapat dukungan dari DPRD Kota Palangka Raya.

Wakil Ketua I Komisi II DPRD Kota Palangka Raya, Hap Baperdu menilai langkah antisipatif melalui rapat koordinasi lintas instansi serta patroli terpadu merupakan langkah yang tepat, mengingat prediksi musim kemarau tahun ini datang lebih awal.

“Kami mendukung penuh kesiapsiagaan pemerintah kota. Apalagi berdasarkan prakiraan, musim kemarau akan lebih kering sehingga potensi karhutla meningkat,” ujarnya saat dimintai tanggapan, Rabu (22/4/2026).

Ia menekankan, selain kesiapan personel dan sarana prasarana, pengawasan di lapangan harus diperkuat. Terutama di wilayah rawan seperti Kecamatan Jekan Raya, Pahandut, dan Sebangau yang kerap terjadi kebakaran lahan.

Menurutnya, peran masyarakat juga menjadi kunci dalam pencegahan karhutla, sehingga sosialisasi harus terus digencarkan hingga tingkat kelurahan.

“Pembentukan Kelurahan Tangguh Bencana ini bagus, tinggal bagaimana implementasinya benar-benar berjalan. Masyarakat harus dilibatkan aktif, karena sebagian besar kasus karhutla dipicu oleh aktivitas manusia,” jelasnya.

Lebih lanjut, ia meminta pemerintah kota memastikan ketersediaan peralatan pemadaman serta dukungan anggaran yang memadai, agar penanganan dapat dilakukan secara cepat dan efektif saat terjadi kebakaran.

“Jangan sampai saat kejadian, kita terkendala alat atau sumber daya. Antisipasi harus lebih diutamakan daripada penanganan,” tegasnya.

Ia juga mengimbau masyarakat untuk tidak membuka lahan dengan cara membakar, karena selain melanggar hukum, juga berpotensi menimbulkan dampak luas bagi lingkungan dan kesehatan.(jef)

PALANGKA RAYA, PROKALTENG.CO– Upaya Pemerintah Kota Palangka Raya melalui BPBD dalam mematangkan kesiapsiagaan menghadapi potensi kebakaran hutan dan lahan (karhutla) mendapat dukungan dari DPRD Kota Palangka Raya.

Wakil Ketua I Komisi II DPRD Kota Palangka Raya, Hap Baperdu menilai langkah antisipatif melalui rapat koordinasi lintas instansi serta patroli terpadu merupakan langkah yang tepat, mengingat prediksi musim kemarau tahun ini datang lebih awal.

“Kami mendukung penuh kesiapsiagaan pemerintah kota. Apalagi berdasarkan prakiraan, musim kemarau akan lebih kering sehingga potensi karhutla meningkat,” ujarnya saat dimintai tanggapan, Rabu (22/4/2026).

Ia menekankan, selain kesiapan personel dan sarana prasarana, pengawasan di lapangan harus diperkuat. Terutama di wilayah rawan seperti Kecamatan Jekan Raya, Pahandut, dan Sebangau yang kerap terjadi kebakaran lahan.

Menurutnya, peran masyarakat juga menjadi kunci dalam pencegahan karhutla, sehingga sosialisasi harus terus digencarkan hingga tingkat kelurahan.

“Pembentukan Kelurahan Tangguh Bencana ini bagus, tinggal bagaimana implementasinya benar-benar berjalan. Masyarakat harus dilibatkan aktif, karena sebagian besar kasus karhutla dipicu oleh aktivitas manusia,” jelasnya.

Lebih lanjut, ia meminta pemerintah kota memastikan ketersediaan peralatan pemadaman serta dukungan anggaran yang memadai, agar penanganan dapat dilakukan secara cepat dan efektif saat terjadi kebakaran.

“Jangan sampai saat kejadian, kita terkendala alat atau sumber daya. Antisipasi harus lebih diutamakan daripada penanganan,” tegasnya.

Ia juga mengimbau masyarakat untuk tidak membuka lahan dengan cara membakar, karena selain melanggar hukum, juga berpotensi menimbulkan dampak luas bagi lingkungan dan kesehatan.(jef)


----------------------------
Hasil Ringkasan Modelmu: Kebakaran hutan dan lahan (karhutla) mendapat dukungan dari DPRD Kota Palangka Raya melalui BPBD dalam mematangkan kesiapsiagaan menghadapi potensi kebakaran hutan dan lahan (karhutla) pada Rabu (22/4/2026).